---
kind: pipeline
name: test
type: docker

trigger:
  ref:
    - refs/heads/dev
    - refs/heads/GET-*

steps:
  - name: install
    image: composer
    commands:
      - composer install --ignore-platform-reqs

  #- name: test
  #  image: laradock/workspace:latest-7.4
  #  environment:
  #    DB_CONNECTION: mysql
  #    DB_HOST: mysql
  #    DB_USERNAME: root
  #    DB_DATABASE: test
  #    DB_PASSWORD: ""
  #    REDIS_HOST: redis
  #    MAIL_MAILER: log
  #    MAIL_FROM_ADDRESS: hello@takeoutmedia.xyz
  #    MAIL_FROM_NAME: Takeout Media
  #  commands:
  #    - ./vendor/bin/phpunit --configuration phpunit.xml

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      port: 22
      rm: true
      target: /var/www/getly/api.getly.app
      source:
        - ./*
    when:
      branch:
        - dev

  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      script:
        - cp /var/www/envs/getly/.env.staging /var/www/getly/api.getly.app/.env
        - pushd /var/www/getly/api.getly.app
        - sudo chown -R $USER:www-data storage
        - sudo chown -R $USER:www-data bootstrap/cache
        - chmod -R 775 storage
        - chmod -R 775 bootstrap/cache
        - chown -R www-data:www-data ./storage/
        - php artisan migrate --force
        - php artisan key:generate
        - php artisan queue:restart
    when:
      branch:
        - dev

  #- name: slack
  #  image: plugins/slack
  #  settings:
  #    webhook:
  #      from_secret: SLACK_WEBHOOK
  #    channel:
  #      from_secret: SLACK_CHANNEL
  #  when:
  #  status: [ success, failure ]

services:
  - name: redis
    image: redis

  - name: mysql
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
